oci:
  region: "eu-frankfurt-1"
git:
  username: "your-github-username"
  repository_url: "https://github.com/your-username/your-repo.git"
ssh:
  public_key_path: "~/.ssh/id_rsa.pub"
cloudflare:
  domain: "yourdomain.com"
  subdomain: "prod"
app:
  name: "k3s-cluster"
  environment: "prod"
  tenant: "hs"
  stage: "prod"