apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: www
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: www=ghcr.io/fapiper/fabianpiper.com/www
    argocd-image-updater.argoproj.io/www.update-strategy: latest
    argocd-image-updater.argoproj.io/www.allow-tags: regexp:^main-.*$
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    argocd-image-updater.argoproj.io/git-repository: https://github.com/fapiper/fabianpiper.com.git
spec:
  project: default
  source:
    repoURL: https://github.com/fapiper/fabianpiper.com.git
    targetRevision: HEAD
    path: argocd/apps/www
  destination:
    server: https://kubernetes.default.svc
    namespace: www
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
