apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: www
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fapiper/fabianpiper.com.git
    targetRevision: HEAD
    path: argocd/apps/www
  destination:
    server: https://kubernetes.default.svc
    namespace: www
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
