apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: argocd-image-updater
    repo: https://argoproj.github.io/argo-helm
    version: 0.11.0
    releaseName: argocd-image-updater
    namespace: argocd
    valuesInline:
      config:
        git:
          user: github-actions[bot]
          email: github-actions[bot]@users.noreply.github.com
        registries:
          - name: ghcr
            prefix: ghcr.io
            api_url: https://ghcr.io
            credentials: pullsecret:argocd/regcred
            default: true