apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/envoyproxy/gateway/releases/download/v1.1.0/install.yaml
  - gateway.yaml

patches:
  - target:
      kind: EnvoyProxy
      name: custom-proxy-config
    patch: |-
      - op: replace
        path: /spec/provider/kubernetes/envoyService/type
        value: ClusterIP